#include "LanguageManager.h"
#include <unordered_map>

EditorLanguage LanguageManager::currentLanguage_ = EditorLanguage::Japanese;

const char* LanguageManager::Tr(const char* englishText) {
    if (currentLanguage_ == EditorLanguage::English) {
        return englishText;
    }

    static const std::unordered_map<std::string, std::string> dictionary = {
        {"Settings", "設定"},
        {"Language", "言語"},
        
        {"Hierarchy", "ヒエラルキー"},
        {"Scene", "シーン"},
        {"Inspector", "インスペクター"},
        {"Name: %s", "名前: %s"},
        {"Active", "アクティブ"},
        {"No object selected.", "オブジェクトが選択されていません。"},
        
        {"Transform", "トランスフォーム"},
        {"Position", "位置"},
        {"Rotation", "回転"},
        {"Scale", "スケール"},
        {"Components", "コンポーネント"},
        {"Add Component", "コンポーネントを追加"},
        
        {"Material", "マテリアル"},
        {"Shader Selection", "シェーダー選択"},
        {"Blend Selection", "ブレンド選択"},
        {"Texture:", "テクスチャ:"},
        {"None", "なし"},
        
        {"Light Settings", "ライト設定"},
        {"Directional Light", "平行光源"},
        {"Point Light", "点光源"},
        {"Spot Light", "スポットライト"},
        {"Remove", "削除"},
        {"Directional Lights", "平行光源 (複数)"},
        {"Add Directional Light", "平行光源を追加"},
        {"Point Lights", "点光源 (複数)"},
        {"Add Point Light", "点光源を追加"},
        {"Spot Lights", "スポットライト (複数)"},
        {"Add Spot Light", "スポットライトを追加"},
        {"Color", "カラー"},
        {"Direction", "方向"},
        {"Intensity", "強度"},
        {"Radius", "半径"},
        {"Decay", "減衰"},
        {"Distance", "距離"},
        {"Angle", "角度"},
        {"Falloff", "フォールオフ"},
        
        // Particle Editor
        {"Emitter Settings", "エミッター設定"},
        {"Spawn Area Scale", "発生範囲スケール"},
        {"Count", "発生数"},
        {"Frequency", "発生頻度"},
        {"Frequency Time", "発生間隔時間"},
        {"Particle Initial Settings", "パーティクル初期設定"},
        {"Base Position", "基本位置"},
        {"Base Size (Scale)", "基本サイズ"},
        {"Base Rotation", "基本回転"},
        {"LifeTime", "寿命"},
        {"Particle Movement Settings", "パーティクル移動設定"},
        {"Base Velocity", "基本速度"},
        {"Velocity Variance", "速度のばらつき"},
        {"Acceleration (Gravity)", "加速度 (重力)"},
        {"Size Variance", "サイズのばらつき"},
        {"Size Multiplier", "サイズ倍率"},
        {"Visual Settings", "見た目の設定"},
        {"Billboard", "ビルボード"},
        {"Shape", "形状"},
        {"Blend Mode", "ブレンドモード"},
        {"Cylinder Divide", "円柱分割数"},
        {"Cylinder Top Radius", "円柱上部半径"},
        {"Cylinder Bottom Radius", "円柱下部半径"},
        {"Cylinder Height", "円柱の高さ"},
        {"Ring Divide", "リング分割数"},
        {"Ring Outer Radius", "リング外半径"},
        {"Ring Inner Radius", "リング内半径"},
        {"Add Particle", "パーティクル追加"},
        {"stop", "停止"},
        {"IsHit", "当たり判定有効"},
        {"Active Particles: %d", "アクティブなパーティクル: %d"},
        {"File Name", "ファイル名"},
        {"Saved Particles", "保存済みパーティクル"},
        {"Save JSON", "JSONを保存"},
        {"Load JSON", "JSONを読み込み"},
        {"(Drag and drop an image from the Resources window)", "(リソースウィンドウから画像をドラッグ＆ドロップ)"},
        {"Emitter Type", "エミッタータイプ"},
        {"Outer Radius", "外半径"},
        {"Inner Radius", "内半径"},
        {"Radial Velocity", "放射初速"},
        {"Spread Angle", "広がり角度"},
        {"Speed", "初速度"},
        {"Spawn / Burst Mode", "発生 / バーストモード"},
        {"Loop Emission", "ループ発生"},
        {"Burst Count", "バースト数"},
        {"Trigger Burst", "バースト発生 (単発)"},
        {"Align to Velocity", "進行方向を向く"},
        {"Base Color", "基本カラー"},
        {"Scale Over Lifetime", "スケールの時間変化"},
        {"Enable Scale Over Lifetime", "スケール時間変化を有効化"},
        {"Curve Type", "カーブ形式"},
        {"Start Scale", "開始スケール"},
        {"End Scale", "終了スケール"},
        {"Peak Scale", "ピークスケール"},
        {"Color Over Lifetime", "カラーの時間変化"},
        {"Enable Color Over Lifetime", "カラー時間変化を有効化"},
        {"Start Color", "開始カラー"},
        {"End Color", "終了カラー"},
        {"Radial Speed", "放射速度"},
        {"Radial Speed Variance", "放射速度のばらつき"},
        {"Cube Size", "キューブサイズ"},

        {"Preview", "プレビュー"},
        {"Controls:", "コントロール:"},
        {"Gizmo Operation", "ギズモ操作"},
        {"Play / Pause", "再生 / 一時停止"},
        {"Clear Particles", "パーティクルをクリア"},
        {"Save As...", "名前を付けて保存..."},
        {"Load...", "読み込み..."},
        {"Save", "保存"},
        {"File operations", "ファイル操作"},
        {"Select Particle JSON file", "パーティクルのJSONファイルを選択"},
        {"Particle Editor", "パーティクルエディター"},
        {"Debug Info", "デバッグ情報"},
        {"Resources", "リソース"},
        {"Logs", "ログ"},
        {"Reset Layout", "レイアウト初期化"},
        {"Layout", "レイアウト"},
        {"Save Layout", "レイアウトを保存"},
        {"Restore Layout", "保存したレイアウトを復元"},
        {"Reset to Default", "デフォルト配置に初期化"},
        {"Layout saved.", "レイアウトを保存しました。"},
        {"Layout restored.", "レイアウトを復元しました。"},
        {"Layout reset to default.", "デフォルト配置に初期化しました。"}
    };

    auto it = dictionary.find(englishText);
    if (it != dictionary.end()) {
        return it->second.c_str();
    }
    return englishText;
}
